import requests
import json
from dataclasses import dataclass, asdict
from typing import List, Optional, Dict, Any

from . import prompts
from . import validator

@dataclass
class Annotation:
    text: str
    annotation: Dict[str, Any]

def call_model(port: str, messages: Dict[str, str], **kwargs: Any) -> Dict[str, Any]:
    """
    Calls a model hosted on a local server with the given messages and additional parameters.
    Expects a LLaMA.cpp style server to be running on the specified port. The messages should be in the format expected by the model, and additional parameters can be passed as keyword arguments.
    """
    url = f"http://localhost:{port}/v1/chat/completions"
    headers = {"Content-Type": "application/json"}
    payload = {
        "model": kwargs.get("model", "DNM"),
        "messages": messages,
        **kwargs
    }
    response = requests.post(url, headers=headers, data=json.dumps(payload))
    return response.json()

class Annotator:
    """
    Base class for annotating text using a model hosted on a local server. It provides methods to annotate individual texts and batch annotate multiple texts, with validation of the annotations using the validator module.

    Subclasses must define a non-empty `role` class attribute (e.g. role = "gloss").
    The role is used as the sentence dict key in Generator and as the template variable name.
    """
    role: str = ""

    def __init__(self, port: str):
        self.port = port

    def annotate(self, text: str, annotation_fn: callable = prompts.create_annotation_prompt) -> Optional[str]:
        """
        Annotates a single text by calling the model with a prompt generated by the provided annotation function. It extracts the JSON content from the model's response and returns it as a string. If the annotation cannot be extracted, it returns None.
        """
        messages = annotation_fn(text)
        response = call_model(self.port, messages)
        return validator.extract_json_from_annotation(response.get("choices", [{}])[0].get("message", {}).get("content", ""))

    def batch_annotate(self, texts: List[str]) -> List[Optional[Annotation]]:
        """
        Annotates a batch of texts by calling the annotate method for each text. It returns a list of Annotation objects.
        """
        annotations = []
        for text in texts:
            annotation = self.annotate(text)
            annotations.append(Annotation(text=text, annotation=annotation))
        return annotations
    
    def save_as_json(self, annotations: List[Annotation], filename: str) -> None:
        """
        Saves a list of Annotation objects to a JSON file with the specified filename. The annotations are saved in a structured format that includes both the original text and the corresponding annotation.
        """
        with open(filename, 'w', encoding='utf-8') as f:
            json.dump([asdict(annotation) for annotation in annotations], f, ensure_ascii=False, indent=4)
    
    def load_annotations_from_json(self, filename: str) -> List[Annotation]:
        """
        Loads annotations from a JSON file with the specified filename and returns a list of Annotation objects. The JSON file is expected to contain a list of objects, each with a "text" field and an "annotation" field.
        """
        with open(filename, 'r', encoding='utf-8') as f:
            data = json.load(f)
            return [Annotation(text=item["text"], annotation=item["annotation"]) for item in data]
    
    def annotate_and_save(self, texts: List[str], filename: str) -> None:
        """
        Annotates a batch of texts and saves the valid annotations to a JSON file. It calls the batch_annotate method to get the annotations and then uses the save_as_json method to save them to the specified filename.
        """
        annotations = self.batch_annotate(texts)
        self.save_as_json(annotations, filename)
        return annotations