# sanjaya configuration

work:
  title: Λυσιστράτη
  author: Aristophanes

source:
  file: /cluster/tufts/perseuslab/pnadel01/reading-envs/data/tlg0019/tlg007/tlg0019.tlg007.perseus-grc2.xml
  xpath: .//tei:l

output:
  dir: "/cluster/tufts/perseuslab/pnadel01/reading-envs/sanjaya/output/Aristophanes/Λυσιστράτη"

annotators:
  - class: sanjaya.llm.nlp_pipeline_annotators.NLPGlossAnnotator
    args:
        base_url: "http://localhost:8080"
        language: Ancient Greek
        author: Aristophanes
        work: Λυσιστράτη
        prompt: sanjaya.llm.prompts.gloss_prompt_no_pos

  - class: sanjaya.llm.annotators.TranslationAnnotator
    args:
        base_url: "http://localhost:8080"
        language: Ancient Greek
        author: Aristophanes
        work: Λυσιστράτη

  - class: sanjaya.llm.annotators.CommentAnnotator
    args:
        base_url: "http://localhost:8080"
        language: Ancient Greek
        author: Aristophanes
        work: Λυσιστράτη
        classifier_prompt: sanjaya.llm.prompts.comment_classifier_prompt
        writer_prompt: sanjaya.llm.prompts.comment_writer_prompt
        